import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

export interface GenerationResult {
  imageUrl: string;
  medium: string;
}

export async function visualizeProduct(
  base64Image: string,
  mimeType: string,
  medium: string
): Promise<string> {
  const model = "gemini-2.5-flash-image";
  
  const prompt = `Place the product from this image onto a ${medium}. 
  The product should look exactly like it does in the original image, maintaining its colors, logo, and shape perfectly. 
  The ${medium} should be in a professional, high-quality marketing photography setting. 
  Ensure the product is the central focus and is integrated naturally into the ${medium}.`;

  const response = await ai.models.generateContent({
    model: model,
    contents: {
      parts: [
        {
          inlineData: {
            data: base64Image,
            mimeType: mimeType,
          },
        },
        {
          text: prompt,
        },
      ],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No image was generated by the model.");
}
